spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=root
spring.datasource.password=aditya
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always